// import type { Metadata } from "next";
// import { Inter } from "next/font/google";

import { Typography } from "@mui/material";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Typography
        gutterBottom
        variant='h5'
        component='div'
        sx={{ color: "text.primary" }}
      >
        Form login
      </Typography>
      {children}
    </div>
  );
}
