import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ThemeRegistry from "./utils/ThemeRegistry";
import Header from "./component/Header";
import AuthProvider from "./context/authContext";
import { cookies } from "next/headers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const storeCookies = cookies();
  const sessionToken = storeCookies.get("sessionToken") || { value: "" };
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>
        <AuthProvider initialSessionToken={sessionToken?.value}>
          <ThemeRegistry options={{ key: "mui-theme" }}>
            <Header />
            {children}
          </ThemeRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
